sudo: required
language: python
services: 
    - docker
python:
  - "2.7"
  - "3.5"
install: 
    - "pip install -r requirements.txt"  
    - "docker build -t final_base ."
# command to run tests
script: 
    - ./gateway/test.sh 
