# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='client',
        ),
        migrations.AddField(
            model_name='command',
            name='transaction_uuid',
            field=models.CharField(default='aaaaaaaaaaaaaaaaaaaa', max_length=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.Command'),
        ),
    ]
