# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_auto_20170116_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
