version: "2"

services:
  subscriber:
    build: .
    links:
    - db
    - mq
    command: python3 saver/run_subscriber.py
  api:
    build: .
    links:
    - db
    ports:
    - 8000:80
    command: python3 saver/manage.py runserver 0.0.0.0:80
  mq:
    image: rabbitmq
    ports:
    - 5672:5672
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - ./db:/var/lib/postgresql/data
